### PR TITLE
Minor bug fix

### PR DESCRIPTION
**Pull request by dgiangrave**
Minor inconsistency bug fix. fps_limit variable lives at top level of JSON object, not in particles.

Noticed you have a different implementation on your website than in this repo, where you have the fps var both at the top level AND in the particles sub object. By removing the reference to the particles sub object in the script, it fixes this respective implementation.

### CODE REVIEW

**Comment by caldempsey** [comment]
Thank you for this! This was the first contribution of my career so I apologize for the inconsistency. I'll get this sorted right away. You're a really great person for going through the trouble for letting me know, and clearly a good developer for spotting it too!

Very best,
Callum Dempsey Leach
www.callumleach.com
________________________________

**Review by caldempsey — APPROVED** [review]
❤️💛💚💙💜

**Comment by dgiangrave** [comment]
Glad I could help! I greatly appreciate your contribution, it actually helped me with another issue aside from CPU usage; particles moving at different speeds dependent on cpu power creating huge inconsistencies across devices. It makes me wonder, why your contribution hasn't been added to the main branch of particles.js. Keep up the good work!

**Comment by caldempsey** [comment]
The main branch of particles.js hasn’t been updated but the implementation delivered on node package manager as a react component has been, so if you’re playing with React I’d check out that. I’m not on a PC right now so it’s difficult for me to pull it up for you but if you struggle to find it don’t hesitate to let me know!

**Pull request merged**
